export const HomeActionTypes = {
	GET_REPOS_BY_USERNAME : 'GET_REPOS_BY_USERNAME',
	GET_REPOS_BY_USERNAME_PENDING : 'GET_REPOS_BY_USERNAME_PENDING',
	GET_REPOS_BY_USERNAME_FULFILLED : 'GET_REPOS_BY_USERNAME_FULFILLED',
	GET_REPOS_BY_USERNAME_REJECTED : 'GET_REPOS_BY_USERNAME_REJECTED',
}
